spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/meta_db?authSource=admin
      database: meta_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  messaging:
    stomp:
      broker-relay:
        host: localhost  # RabbitMQ 서버 IP
        port: 61613           # STOMP 기본 포트
        system-login: admin   # RabbitMQ 로그인 계정
        system-passcode: admin
        client-login: admin
        client-passcode: admin

app:
  oauth2:
    providers:
      google:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
        redirectUri: "http://localhost:8080/rest-api/v1/oauth2/google"
        tokenUri: "https://oauth2.googleapis.com/token"
        userInfoUri: "https://www.googleapis.com/oauth2/v3/userinfo"
      naver:
        clientId: ${NAVER_CLIENT_ID}
        clientSecret: ${NAVER_CLIENT_SECRET}
        redirectUri: "http://localhost:8080/rest-api/v1/oauth2/naver"
        tokenUri: "https://nid.naver.com/oauth2.0/token"
        userInfoUri: "https://openapi.naver.com/v1/nid/me"
      kakao:
        clientId: ${KAKAO_CLIENT_ID}
        redirectUri: "http://localhost:8080/rest-api/v1/oauth2/kakao"
        tokenUri: "https://kauth.kakao.com/oauth/token"
        userInfoUri: "https://kapi.kakao.com/v2/user/me"

frontend:
  oauth-redirect: http://localhost:5173/login

logging:
  level:
    org.springframework.web: DEBUG
    com.letzgo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.stomp: DEBUG
