server:
  port: 8080

spring:
  application:
    name: letzgo-application
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 52MB
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}  # 환경 변수 사용 권장
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region: ap-northeast-2  # AWS 서울 리전
      s3:
        bucket: letzgo-bucket-v1 # S3 버킷명

schedule:
  use: false
  hotel:
    use-page: 10
    cron: 0 0 0 * * *
  restaurant:
    cron: 0 0 6 * * *

custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expiration: "#{60 * 60 * 1000}"   # 1시간
  refreshToken:
    expiration: "#{60 * 60 * 24 * 7 * 1000}"   # 7일

api-keys:
  google:
    client-key: ${GOOGLE_API_KEY}

selenium:
  remote-url: ${SELENIUM_REMOTE_URL:http://localhost:4444/wd/hub}
