server:
  port: 8080
spring:
  application:
    name: letzgo-application
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 52MB

schedule:
  use: true
  hotel:
      use-page: 10
      cron: 0 0 0 * * *
  restaurant:
      cron: 0 0 6 * * *