custom:
  jwt:
    secretKey: lDTnvgXK8FVtN2kufiWr+3IH1sYnbn74Utejna5VLsElrmA1cysi+/z8AK94E5fHiilIlegehcEPpb5EX4RtNw==
  accessToken:
    expiration: "#{60 * 30}"   # 30분
  refreshToken:
    expiration: "#{60 * 60 * 24 * 7}"   # 7일

api-keys:
  google:
    client-key:

spring:
  datasource:
    password: letzgo77
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}  # 환경 변수 사용 권장
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2  # AWS 서울 리전
      s3:
        bucket: letzgo-bucket-jun2-1 # S3 버킷명
