spring:
  datasource:
    url: jdbc:postgresql://${HOST_DB}:5432/meta_db
    username: admin
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false      # 운영 환경에서는 보통 false로 설정
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://admin:${POSTGRES_PASSWORD}@${HOST_DB}:27017/meta_db?authSource=admin
      database: meta_db
  kafka:
    bootstrap-servers: 54.180.80.251:9092

frontend:
  oauth-redirect: https://www.letzgo.site/login

fcm:
  service-account-file: file:/app/env/fcm-service-account.json
  project-id: 285801023043

logging:
  level:
    org.springframework.web: INFO
    team.letzgo: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN



#RedPanda

#version: '3.8'
#
#services:
#  redpanda:
#    image: docker.redpanda.com/redpandadata/redpanda:latest
#    container_name: redpanda-0
#    restart: unless-stopped
#    command:
#      - redpanda
#      - start
#      - --mode
#      - dev-container
#      - --smp
#      - "1"                   # vCPU 1개만 사용 (t3.small은 2vCPU 이므로 하나만 할당)
#      - --memory
#      - 1G                    # 전체 컨테이너에 1GB 메모리 할당 (2GB 중 절반)
#      - --reserve-memory
#      - 512M                  # 최소 512MB는 Redpanda가 항상 확보
#      - --default-log-level=warn
#      - --kafka-addr
#      - PLAINTEXT://0.0.0.0:9092
#      - --advertise-kafka-addr
#      - PLAINTEXT://54.180.80.251:9092
#      - --pandaproxy-addr
#      - 0.0.0.0:8082
#      - --advertise-pandaproxy-addr
#      - 54.180.80.251:8082
#      - --schema-registry-addr
#      - 0.0.0.0:8081
#      - --rpc-addr
#      - 0.0.0.0:33145
#      - --advertise-rpc-addr
#      - 54.180.80.251:33145
#    ports:
#      - "9092:9092"
#      - "8081:8081"
#      - "8082:8082"
#      - "9644:9644"
#    volumes:
#      - redpanda_data:/var/lib/redpanda/data
#    networks:
#      - redpanda_network
#
#volumes:
#  redpanda_data:
#
#networks:
#  redpanda_network:
#    driver: bridge
