server:
  port: 8070
spring:
  application:
    name: letzgo-application
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 42MB
