custom:
  jwt:
    secretKey: lDTnvgXK8FVtN2kufiWr+3IH1sYnbn74Utejna5VLsElrmA1cysi+/z8AK94E5fHiilIlegehcEPpb5EX4RtNw==
  accessToken:
    expiration: "#{60 * 30}"   # 30분
  refreshToken:
    expiration: "#{60 * 60 * 24 * 7}"   # 7일

api-keys:
  google:
    client-key: 