spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/meta_db?authSource=admin
      database: meta_db
  kafka:
    bootstrap-servers: localhost:9092

frontend:
  oauth-redirect: http://localhost:5173/login

fcm:
  service-account-file: classpath:fcm-service-account.json
  project-id: 30409426097

logging:
  level:
    org.springframework.web: DEBUG
    com.letzgo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.stomp: DEBUG
