spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/meta_db?authSource=admin
      database: meta_db
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  messaging:
    stomp:
      broker-relay:
        host: localhost  # RabbitMQ 서버 IP
        port: 61613           # STOMP 기본 포트
        system-login: admin   # RabbitMQ 로그인 계정
        system-passcode: admin
        client-login: admin
        client-passcode: admin

logging:
  level:
    org.springframework.web: DEBUG
    com.letzgo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.stomp: DEBUG
